# -*- coding: utf-8 -*-
"""Gerador de Senhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9wjSvaVpDwNPCgVedv_BJSflwXkuwMw
"""

import random

# Caracteres usados para formar senhas #
lower = 'abcdefghijklmnopqrstuvxwyz'
upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
numbers = '0123456789'
symbols = '#@$%&*-+/_'

# Agrupa todos os caracteres #
all = lower + upper + numbers + symbols

# Define tamanho da senha #
length = 16

# Gera senha #
password = "".join(random.sample(all, length))

# Mostra o resultado #
print(password)

